name: Deploy Backend to Hugging Face Space

on:
  push:
    branches: ["main"]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face CLI
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub[cli]"

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Prepare Docker Space payload
        run: |
          rm -rf deploy && mkdir -p deploy
          # Copy entire backend directory (keeps module path 'backend.main')
          cp -r backend deploy/backend
          # Copy backend requirements file to root of deploy
          if [ -f backend/requirements.txt ]; then
            cp backend/requirements.txt deploy/requirements.txt
          else
            echo "fastapi" >> deploy/requirements.txt
            echo "uvicorn[standard]" >> deploy/requirements.txt
          fi

          # Create Dockerfile that runs backend.main:app on port 7860
          cat > deploy/Dockerfile << 'EOF'
          FROM python:3.10-slim

          ENV PYTHONDONTWRITEBYTECODE=1 \
              PYTHONUNBUFFERED=1

          WORKDIR /app

          COPY requirements.txt /app/requirements.txt
          RUN pip install --no-cache-dir -r /app/requirements.txt

          # Copy the backend package under /app/backend
          COPY backend /app/backend

          # Ensure /app is on Python path (it is by default as WORKDIR)
          ENV PORT=7860
          EXPOSE 7860

          # Start FastAPI using the package path backend.main:app
          CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "7860"]
          EOF

          # Space metadata (Docker SDK, not Streamlit)
          cat > deploy/README.md << 'EOF'
          ---
          title: TalentScout AI Backend
          emoji: 🤖
          colorFrom: blue
          colorTo: green
          sdk: docker
          pinned: false
          ---
          FastAPI backend (Docker Space) serving at port 7860.
          Swagger: /docs
          EOF

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy
          git init
          git lfs install
          git remote add origin https://user:${HF_TOKEN}@huggingface.co/spaces/Jayanthk2004/TalentScout-Ai
          git add .
          git commit -m "Deploy FastAPI backend (backend.main:app) via GitHub Actions" || echo "No changes to commit"
          git branch -M main
          git push --force origin main
