name: Deploy Backend to Hugging Face Space

on:
  push:
    branches: ["main"]  

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face CLI
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub[cli]"

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Prepare deploy directory with a Dockerized FastAPI backend
      - name: Prepare Docker Space payload
        run: |
          rm -rf deploy && mkdir -p deploy
          # Copy backend sources
          cp -r backend/* deploy/

          # Ensure requirements.txt exists (adjust if your file is named differently)
          if [ ! -f deploy/requirements.txt ]; then
            echo "uvicorn[standard]" >> deploy/requirements.txt
            echo "fastapi" >> deploy/requirements.txt
          fi

          # Create Dockerfile for FastAPI on port 7860
          cat > deploy/Dockerfile << 'EOF'
          FROM python:3.10-slim
          ENV PYTHONDONTWRITEBYTECODE=1 \
              PYTHONUNBUFFERED=1
          WORKDIR /app
          COPY requirements.txt /app/requirements.txt
          RUN pip install --no-cache-dir -r /app/requirements.txt
          COPY . /app
          # Spaces proxy expects Docker Spaces to listen on 7860
          ENV PORT=7860
          CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
          EOF

          # Space metadata: set sdk to docker (not streamlit)
          cat > deploy/README.md << 'EOF'
          ---
          title: TalentScout AI Backend
          emoji: 🤖
          colorFrom: blue
          colorTo: green
          sdk: docker
          pinned: false
          ---
          FastAPI backend for TalentScout AI (Docker Space).
          - Exposes uvicorn on port 7860
          - Use the Space base URL as BACKEND_URL in the frontend
          EOF

      - name: Push to Hugging Face Space (Docker)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy
          git init
          git lfs install
          # Replace owner/space with your Space path
          git remote add origin https://user:${HF_TOKEN}@huggingface.co/spaces/Jayanthk2004/TalentScout-Ai
          git add .
          git commit -m "Deploy FastAPI backend via GitHub Actions" || echo "No changes to commit"
          git branch -M main
          git push --force origin main
