name: Deploy Backend to Hugging Face Space

on:
  push:
    branches: [ "main" ]  

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install huggingface CLI
      - name: Install huggingface CLI
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      # 4️⃣ Configure git
      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # 5️⃣ Prepare deployment folder
      - name: Prepare backend for deployment
        run: |
          mkdir deploy
          cp -r backend/* deploy/

          # Add a minimal README for Hugging Face
          cat <<EOT >> deploy/README.md
---
title: TalentScout AI Backend
emoji: 🤖
colorFrom: blue
colorTo: green
sdk: streamlit
sdk_version: "1.27.0"
app_file: main.py
pinned: false
---
Minimal backend deployment for TalentScout AI.
EOT

      # 6️⃣ Install backend requirements
      - name: Install backend requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements.txt

      # 7️⃣ Push to Hugging Face Space
      - name: Push backend to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy
          git init
          git lfs install
          git remote add origin https://user:$HF_TOKEN@huggingface.co/spaces/Jayanthk2004/TalentScout-Ai
          
          git add .
          git commit -m "Auto deploy backend from GitHub Actions" || echo "No changes to commit"
          git branch -M main
          git push --force origin main
